#!bin/bash

USERID=$(id -u)
if [ $USERID -ne 0 ]; then
    echo "ERROR:: please run this script with root prevlege"
    exit 1 #failure is other then 0
fi
VALIDATE(){ # functions receives inputs through args just like shell script args
if [ $1 -ne 0 ]; then  
    echo "ERROR:: installing $2 is failure"
    exit 1
else
    echo "Installing $2 is SUCCESS" 
fi
}
#// mysql installation
dnf install mysql -y
VALIDATE $? "MYSQL"

dnf install nginx -y
VALIDATE $? "nginx"

dnf install python3
VALIDATE $? "python3"

